compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
  eslint-plugin-canonical@*:
    dependencies:
      "@typescript-eslint/types": "*"
  unplugin-dts@*:
    dependencies:
      "@microsoft/api-extractor": "*"

yarnPath: .yarn/releases/yarn-4.9.2.cjs
