compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "@storybook/builder-vite@*":
    dependencies:
      "@storybook/addon-docs": 7.6.6
      react: ^18.2.0
      react-dom: ^18.2.0
  "@storybook/core-common@*":
    dependencies:
      "@storybook/react-vite": 7.6.6
      react: ^18.2.0
      react-dom: ^18.2.0
      vite: ^4.4.9
  "@storybook/docs-tools@*":
    dependencies:
      react: ^18.2.0
      react-dom: ^18.2.0

yarnPath: .yarn/releases/yarn-4.1.1.cjs
