compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
    eslint-plugin-canonical@*:
        dependencies:
            '@typescript-eslint/types': '*'

yarnPath: .yarn/releases/yarn-4.6.0.cjs
